- name: Deploy of the AD platform
  community.general.terraform:
    project_path: "roles/terraform/project"
    force_init: true
    state: present
    complex_vars: true
    variables:
      cluster_address: "{{ cluster_address }}"
      instances_type: "{{ instances_type }}"
      networks: "{{ networks }}"
      project_name: "{{ project_name }}"
      remote: "{{ remote }}"
      teams: "{{ teams }}"
  run_once: true
  delegate_to: localhost
  connection: local

- name: Create network peer between gameserver-network and vulnboxes-network
  shell:
    cmd: "incus network peer create gameserver-network peer1 vulnboxes-network"
  run_once: true

- name: Create network peer between vulnboxes-network and gameserver-network
  shell:
    cmd: "incus network peer create vulnboxes-network peer1 gameserver-network"
  run_once: true

- name: Create network peer between vulnboxes-network and vpn-servers-network
  shell:
    cmd: "incus network peer create vulnboxes-network peer2 vpn-servers-network"
  run_once: true

- name: Create network peer between vpn-servers-network and vulnboxes-network
  shell:
    cmd: "incus network peer create vpn-servers-network peer2 vulnboxes-network"
  run_once: true
