- name: "Install cluster requirements"
  apt:
    name:
      - incus
      - qemu-system
    state: latest
    update_cache: yes
  become: yes

- name: "Install rsync for clustering"
  apt:
    name: rsync
    state: latest
    update_cache: yes
  become: yes
  when: ansible_play_hosts | length > 2

- block:
  - name: "Copy init file on incus server"
    template:
      src: templates/server.yaml.j2
      dest: /tmp/init.yaml

  - name: "Set up incus server"
    shell: incus admin init --preseed < /tmp/init.yaml
    become: yes

  when: ansible_play_hosts | length == 1

- block:
  - name: Set server_name
    set_fact:
      server_name: "{{ nodes_names[inventory_hostname] }}"

  - name: Set local as current host
    set_fact:
      server_address: "{{ inventory_hostname }}"

  - block:
    - name: "Copy init file on boostrap server"
      template:
        src: templates/bootstrap.yaml.j2
        dest: /tmp/init.yaml

    - name: "Set up bootstrap server"
      shell: incus admin init --preseed < /tmp/init.yaml
      become: yes

    when: inventory_hostname == server_1

  - name: "Generate node token"
    shell: "incus cluster --force-local --quiet add {{ inventory_hostname }}"
    register: token
    when: inventory_hostname != server_1

  - block:
    - name: Wait 5s to avoid token use before valid
      ansible.builtin.wait_for:
        timeout: 5
      delegate_to: localhost
      when: 'token.changed'

    - name: "Copy init file on other nodes"
      throttle: 1
      template:
        src: templates/cluster-member.yaml.j2
        dest: /tmp/init.yaml

    - name: "Set up cluster members"
      shell: incus admin init --preseed < /tmp/init.yaml
      become: yes
    
    when: token.changed

  - block:
    - name: "Set ovn-northd-nb-db"
      set_fact:
        ovn_northd_nb_db: tcp:{{ server_1 }}:6641,tcp:{{ server_2 }}:6641,tcp:{{ server_3 }}:6641

    - name: "Make ovn communicate with incus"
      shell: "incus config set network.ovn.northbound_connection {{ ovn_northd_nb_db }}"
      become: yes

    when: inventory_hostname == server_1
  
  when: ansible_play_hosts | length > 2

- block: 
  - name: Upload incus certificate
    copy:
      src: ~/.config/incus/client.crt
      dest: /tmp/client.crt

  - name: Trust client
    shell: incus config trust add-certificate /tmp/client.crt
    become: yes

  when: inventory_hostname == server_1

- name: Add remote
  shell: incus remote add {{ remote }} {{ server_1 }} --accept-certificate
  run_once: true
  connection: local
  delegate_to: localhost