- name: Install Fauscteam Gameserver
  include_role:
    name: "{{ faus_role }}"
  loop:
    - fausecteam.ctf_gameserver_ansible.db_prolog
    - fausecteam.ctf_gameserver_ansible.web
    - fausecteam.ctf_gameserver_ansible.db_epilog
    - fausecteam.ctf_gameserver_ansible.controller
    - fausecteam.ctf_gameserver_ansible.submission
    - fausecteam.ctf_gameserver_ansible.checker
    - fausecteam.ctf_gameserver_ansible.vpnstatus
  loop_control:
    loop_var: "faus_role"

- name: Upload uwsgi configuration
  template:
    src: "files/ctf-gameserver.ini"
    dest: "/etc/uwsgi/apps-enabled/"
  notify: Restart Uwsgi

- name: Upload nginx configuration
  template:
    src: "files/ctf-gameserver.conf"
    dest: "/etc/nginx/sites-enabled/ctf-gameserver.conf"

- name: Delete default conf nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx
