- name: "Generate node token"
  shell: incus cluster add {{ item }} | grep -v ":"
  register: output

- name: "Create tokens"
  set_fact:
    tokens: "{{ tokens | default({}) | combine ({ item: output.stdout }) }}"