- name: Configure gameserver
  hosts: gameserver
  
  roles:
    - fausecteam.ctf_gameserver_ansible.db_prolog
    - fausecteam.ctf_gameserver_ansible.web
    - fausecteam.ctf_gameserver_ansible.db_epilog
    - fausecteam.ctf_gameserver_ansible.controller
    - fausecteam.ctf_gameserver_ansible.submission
    - fausecteam.ctf_gameserver_ansible.checker
    - fausecteam.ctf_gameserver_ansible.vpnstatus

  tasks:
    - name: Upload uwsgi configuration
      template:
        src: "../templates/gameserver/ctf-gameserver.ini"
        dest: "/etc/uwsgi/apps-enabled/"

    - name: Upload nginx configuration
      template:
        src: ../templates/gameserver/gameserver.conf.j2
        dest: "/etc/nginx/sites-enabled/ctf-gameserver.conf"

    - name:
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      systemctl:
        name: nginx
        state: restarted

    - name: Restart Uwsgi
      systemctl:
        name: uwsgi
        state: restarted
