- hosts: cluster_nodes
  roles:
    - ovn
  
- hosts: cluster_nodes
  roles:
    - incus
  tasks:
    - block:
      - name: "Set ovn-northd-nb-db"
        set_fact:
          ovn_northd_nb_db: tcp:{{ server_1 }}:6641,tcp:{{ server_2 }}:6641,tcp:{{ server_3 }}:6641

      - name: "Make ovn communicate with incus"
        shell: "incus config set network.ovn.northbound_connection {{ ovn_northd_nb_db }}"
      
      when: ansible_play_hosts | length > 2 and inventory_hostname == server_1

- hosts: localhost
  connection: local
  tasks:
    - name: Init packer
      shell: packer init ../images/templates
    
    - name: Deploy images
      shell: packer build ../images/templates

    - name: Deploy of the AD platform
      community.general.terraform:
        project_path: '../terraform'
        force_init: true
        state: present
        variables:
          instances_type: "{{ instances_type }}"
          networks: "{{ networks }}"
          remote: "{{ remote }}"
          teams: "{{ teams }}"

- hosts: vulnboxes
  roles:
    - vulnbox

- hosts: vpns
  roles:
    - vpn
