- hosts: cluster_nodes
  serial: 1
  roles:
    - incus
  become: yes

- hosts: localhost
  connection: local
  tasks:
    - name: Init packer
      shell: packer init ../images/templates
    
    - name: Deploy images
      shell: packer build ../images/templates

    - name: Deploy of the AD platform
      community.general.terraform:
        project_path: '../terraform'
        force_init: true
        state: present

- hosts: vulnboxes
  roles:
    - vulnbox

- hosts: vpns
  roles:
    - vpn
