- hosts: cluster_nodes
  any_errors_fatal: true
  roles:
    - ovn
    - incus

- hosts: localhost
  connection: local
  tasks:
    - name: Init packer
      shell: packer init ../images/templates

    - name: Deploy images
      shell: packer build ../images/templates

- hosts: localhost
  connection: local
  roles:
    - terraform

- hosts: vulnboxes
  roles:
    - vulnbox

- hosts: vpns
  roles:
    - vpn

- hosts: faustgameserver
  roles:
    - gameserver
